-- Module + Werk + role authorization for EHS business data.
create or replace function public.ehs_has_module_werk_access(p_org uuid,p_werk uuid,p_product text,p_write boolean default false)
returns boolean language plpgsql stable security definer set search_path=public,pg_temp as $$
declare actor uuid:=auth.uid();begin
  if actor is null or p_org is null or p_werk is null then return false; end if;
  if exists(select 1 from public.ehs_personal_werk_bindings b where b.user_id=actor and b.werk_id=p_werk and b.organization_id=p_org and exists(select 1 from public.ehs_subscriptions s where s.user_id=actor and s.status in ('active','grace','canceled') and (s.expires_at is null or s.expires_at>now()) and s.product_id in (p_product,'ehs_pro_monthly'))) then return true; end if;
  return exists(select 1 from public.ehs_werk_members wm join public.ehs_werks w on w.id=wm.werk_id where wm.user_id=actor and wm.werk_id=p_werk and wm.status='active' and (not p_write or wm.seat_type='editor') and w.organization_id=p_org and p_product=any(w.licensed_modules) and w.billing_status in ('active','grace','canceled') and (w.current_period_end is null or w.current_period_end>now()));
end$$;
create or replace function public.ehs_has_org_module_access(p_org uuid,p_product text,p_write boolean default false) returns boolean language plpgsql stable security definer set search_path=public,pg_temp as $$
declare actor uuid:=auth.uid();begin if actor is null or p_org is null then return false; end if; return exists(select 1 from public.ehs_personal_werk_bindings b where b.user_id=actor and b.organization_id=p_org and exists(select 1 from public.ehs_subscriptions s where s.user_id=actor and s.status in ('active','grace','canceled') and (s.expires_at is null or s.expires_at>now()) and s.product_id in (p_product,'ehs_pro_monthly'))) or exists(select 1 from public.ehs_werk_members wm join public.ehs_werks w on w.id=wm.werk_id where wm.user_id=actor and wm.status='active' and (not p_write or wm.seat_type='editor') and w.organization_id=p_org and p_product=any(w.licensed_modules) and w.billing_status in ('active','grace','canceled') and (w.current_period_end is null or w.current_period_end>now())); end$$;
create or replace function public.ehs_product_for_app_key(p_key text) returns text language sql immutable set search_path=public,pg_temp as $$ select case p_key when 'fluchtplan' then 'ehs_fluchtplan_monthly' when 'brandschutzordnung' then 'ehs_brandschutzordnung_monthly' else null end $$;
revoke all on function public.ehs_has_module_werk_access(uuid,uuid,text,boolean) from public; grant execute on function public.ehs_has_module_werk_access(uuid,uuid,text,boolean) to authenticated;
revoke all on function public.ehs_has_org_module_access(uuid,text,boolean) from public; grant execute on function public.ehs_has_org_module_access(uuid,text,boolean) to authenticated;
revoke all on function public.ehs_product_for_app_key(text) from public; grant execute on function public.ehs_product_for_app_key(text) to authenticated;

drop policy if exists ba_select_member on public.operating_instructions; create policy ba_select_member on public.operating_instructions for select to authenticated using ((origin_werk_id is null and has_org_role(organization_id,array['owner','admin'])) or ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_ba_monthly',false));
drop policy if exists ba_insert_editor on public.operating_instructions; create policy ba_insert_editor on public.operating_instructions for insert to authenticated with check (created_by=auth.uid() and updated_by=auth.uid() and ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_ba_monthly',true));
drop policy if exists ba_update_editor on public.operating_instructions; create policy ba_update_editor on public.operating_instructions for update to authenticated using (ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_ba_monthly',true)) with check (updated_by=auth.uid() and ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_ba_monthly',true));
drop policy if exists ba_delete_admin on public.operating_instructions; create policy ba_delete_admin on public.operating_instructions for delete to authenticated using (has_org_role(organization_id,array['owner','admin']) and (origin_werk_id is null or ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_ba_monthly',true)));

drop policy if exists substances_select_member on public.hazardous_substances; create policy substances_select_member on public.hazardous_substances for select to authenticated using ((origin_werk_id is null and has_org_role(organization_id,array['owner','admin'])) or ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_gefahrstoffkataster_monthly',false));
drop policy if exists substances_insert_editor on public.hazardous_substances; create policy substances_insert_editor on public.hazardous_substances for insert to authenticated with check (ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_gefahrstoffkataster_monthly',true));
drop policy if exists substances_update_editor on public.hazardous_substances; create policy substances_update_editor on public.hazardous_substances for update to authenticated using (ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_gefahrstoffkataster_monthly',true)) with check (ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_gefahrstoffkataster_monthly',true));
drop policy if exists substances_delete_admin on public.hazardous_substances; create policy substances_delete_admin on public.hazardous_substances for delete to authenticated using (has_org_role(organization_id,array['owner','admin']) and (origin_werk_id is null or ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_gefahrstoffkataster_monthly',true)));

drop policy if exists app_records_select_member on public.app_records; create policy app_records_select_member on public.app_records for select to authenticated using ((origin_werk_id is null and has_org_role(organization_id,array['owner','admin'])) or (ehs_product_for_app_key(app_key) is not null and ehs_has_module_werk_access(organization_id,origin_werk_id,ehs_product_for_app_key(app_key),false)));
drop policy if exists app_records_insert_owner on public.app_records; create policy app_records_insert_owner on public.app_records for insert to authenticated with check (owner_user_id=auth.uid() and updated_by=auth.uid() and ehs_product_for_app_key(app_key) is not null and ehs_has_module_werk_access(organization_id,origin_werk_id,ehs_product_for_app_key(app_key),true));
drop policy if exists app_records_update_owner_or_admin on public.app_records; create policy app_records_update_owner_or_admin on public.app_records for update to authenticated using (ehs_product_for_app_key(app_key) is not null and ehs_has_module_werk_access(organization_id,origin_werk_id,ehs_product_for_app_key(app_key),true)) with check (ehs_product_for_app_key(app_key) is not null and ehs_has_module_werk_access(organization_id,origin_werk_id,ehs_product_for_app_key(app_key),true));
drop policy if exists app_records_delete_owner_or_admin on public.app_records; create policy app_records_delete_owner_or_admin on public.app_records for delete to authenticated using (ehs_product_for_app_key(app_key) is not null and ehs_has_module_werk_access(organization_id,origin_werk_id,ehs_product_for_app_key(app_key),true));

drop policy if exists documents_select_member on public.documents; create policy documents_select_member on public.documents for select to authenticated using ((origin_werk_id is null and has_org_role(organization_id,array['owner','admin'])) or (scope='werk' and ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_dokumentmanagement_monthly',false)) or (scope in ('germany','international') and ehs_has_org_module_access(organization_id,'ehs_dokumentmanagement_monthly',false)));
drop policy if exists documents_insert_creator on public.documents; create policy documents_insert_creator on public.documents for insert to authenticated with check (creator_user_id=auth.uid() and ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_dokumentmanagement_monthly',true));
drop policy if exists documents_update_draft on public.documents; create policy documents_update_draft on public.documents for update to authenticated using (status in ('draft','changes_requested') and ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_dokumentmanagement_monthly',true)) with check (status in ('draft','changes_requested') and ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_dokumentmanagement_monthly',true));
drop policy if exists documents_delete_admin on public.documents; create policy documents_delete_admin on public.documents for delete to authenticated using (has_org_role(organization_id,array['owner','admin']) and (origin_werk_id is null or ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_dokumentmanagement_monthly',true)));

drop policy if exists incidents_member_read on public.incidents; create policy incidents_member_read on public.incidents for select to authenticated using ((origin_werk_id is null and has_org_role(organization_id,array['owner','admin'])) or ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_unfallmanagement_monthly',false));
drop policy if exists incidents_member_insert on public.incidents; create policy incidents_member_insert on public.incidents for insert to authenticated with check (created_by=auth.uid() and ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_unfallmanagement_monthly',true));
drop policy if exists incidents_editor_update on public.incidents; create policy incidents_editor_update on public.incidents for update to authenticated using (ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_unfallmanagement_monthly',true)) with check (ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_unfallmanagement_monthly',true));
drop policy if exists incidents_admin_delete on public.incidents; create policy incidents_admin_delete on public.incidents for delete to authenticated using (has_org_role(organization_id,array['owner','admin']) and (origin_werk_id is null or ehs_has_module_werk_access(organization_id,origin_werk_id,'ehs_unfallmanagement_monthly',true)));
